[project]
name = "ocr-rag-qa"
version = "0.1.0"
description = "Simple repository for OCR and RAG Question Answering"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mistralai>=1.6.0",
]

[dependency-groups]
dev = [
    "markdown>=3.8",
    "python-dotenv>=1.1.0",
    "qdrant-client>=1.13.3",
    "requests>=2.32.3",
]
